#!/bin/sh

# This setup script is run by ScraperWiki when the spreadsheet-tool is installed.
# It moves all the neccessary files into the box's http directory.

cd $(dirname $0)
mv js css img index.html ~/http
